import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { IPageProps } from "../interfaces/IPageProps";
import ListWidget from "../widgets/ListWidget";
import clientPromise from "../../lib/mongodb";
import IAppConfig from "../interfaces/IAppConfig";

const Home: NextPage<IPageProps> = ({ host, variant }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{host}</div>
        <ListWidget variant={variant as number} />
      </main>
    </div>
  );
};

export async function getServerSideProps(
  ctx: NextPageContext
): Promise<{ props: IPageProps }> {
  //will get from ctx?.req?.headers.host,

  const regexExp = /\.(.+)/;

  let host = ctx?.req?.headers?.host as string;
  const match = host.match(regexExp);
  const domain = match && match[1] ? (match[1] as string) : "unbranded";

  console.log({ domain });

  const client = await clientPromise;
  const db = client.db("app_config");
  const brand = await db.collection<IAppConfig>("brands").findOne({ domain });

  console.log({ brand });

  return {
    props: {
      variant: brand?.variant as number,
      host: ctx?.req?.headers.host as string,
      domain,
      title: brand?.title as string,
    },
  };
}

export default Home;
