import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import ListWidget from "../widgets/ListWidget";

type PageType = {
  host: string;
  variant: number;
};

const Home: NextPage<PageType> = ({ host, variant }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ListWidget variant={variant} />
      </main>
    </div>
  );
};

export async function getServerSideProps({ req }: NextPageContext) {
  return { props: {} };
}

export default Home;
